### ISSUE TITLE
Using bitcore both on the client and server

### ISSUE THREAD

**Issue by frabrunelle** [wstucco/meteor-packages#1]
Hi, I would like to be able to use `bitcore` not only on the server but also on the client.

This is required to do client-side validation when I use a package such as [astronomy](https://github.com/jagi/meteor-astronomy) or [simple-schema](https://github.com/aldeed/meteor-simple-schema). I use bitcore to validate that the bitcoin address entered by the user is valid.

I think it would work if I just make a package with the `bitcore-lib.js` browser bundle (which I can get from [here](https://github.com/bitpay/bitcore-lib#building-the-browser-bundle). But I haven't tried just yet. Or maybe by using [browserify](https://github.com/elidoran/cosmos-browserify)?

I was just wondering if you are willing to make updates to your package and if you would like to collaborate with me :smiley: That way there are not multiple bitcore Meteor packages to choose from. Otherwise I will go ahead and create my own package (which I am thinking of calling `bitcore-lib` since BitPay just moved [bitcore](https://github.com/bitpay/bitcore) to [bitcore-lib](https://github.com/bitpay/bitcore-lib) [**recently**](https://github.com/bitpay/bitcore-lib/issues/3)).

**Comment by frabrunelle** [comment]
I ended up just making my own package: [frabrunelle:bitcore](https://atmospherejs.com/frabrunelle/bitcore). 

I could have used `bitcore-lib` but I'll wait for Bitpay to at least update their [bitcore.io](http://bitcore.io/) website and make an announcement on their blog. The change was made just a few days ago so I'll see how things evolve.

So what I did is that instead of using the `bitcore` npm package, which would only make the code available on the server (I think it might be possible to expose it on the client as well with [cosmos:browserify](https://github.com/elidoran/cosmos-browserify) but I haven't tried yet, I just used the `bitcore.js` file from `bower install bitcore`. And then I added a file called `export.js` with the following code:

``` javascript
bitcore = require('bitcore');
```

Also relevant:

``` javascript
Package.onUse(function(api) {
  api.versionsFrom('0.9.0');
  api.export('bitcore');
  api.addFiles([
    'bitcore.js',
    'export.js'
  ]);
});
```

Now it works on both the client and server!

**Comment by wstucco** [comment]
Hi, sorry it was night here :)  
I created this package for my colleagues, feel free whatever you want with it.  
I can merge your changes or if you prefer I can link to your repo, if someone is looking for a client/server solution.

**Comment by frabrunelle** [comment]
> I can merge your changes or if you prefer I can link to your repo, if someone is looking for a client/server solution.

That could work, but here is my concern:

Right now when someone searches for a `bitcore` package on [Atmosphere](https://atmospherejs.com/?q=bitcore), they might be confused between `frabrunelle:bitcore` and `mikamai:bitcore`, so it would be worth it to merge our packages.

I can make a PR and once you release the new version I would hide my package from Atmosphere. That way there would only be one `bitcore` package in the search results.

The only thing I'm not sure about is the fact that this repo is called `meteor-packages`. I think it would be better to have a separate repo called `meteor-bitcore`. Let me know if you are okay with creating such a repo :smile: 

The other option would be to use [my repo](https://github.com/frabrunelle/meteor-bitcore) and I could make the update to the package if you add me as a maintainer. You can do so by running this command:

```
meteor admin maintainers mikamai:bitcore --add frabrunelle
```

I'm using this package for a Bitcoin project I am working on and I plan to keep this library up-to-date at least for a few months and probably longer than that. Although I might have to rename the package to `bitcore-lib` in a few weeks once BitPay publicly announces the new name.

So let me know what you prefer between creating your own repo called `meteor-bitcore` or using my repo :smiley:

**Comment by wstucco** [comment]
Hi, I’ve added you to the list of admins, thanks for helping us with this.
